import pymongo

class EntryManager(object):
    from config import getData
    # getData return a dic.
    # {
        # "host": string hostname
        # "port": int
        # "username": string
        # "password": string
    # }

    """Manage entries.
    The structure of an entry:
    {
      '_id': 'optinal field that automatically generated by MongoDB',
      'title': 'Title of an entry',
      'content': 'Markdown content',
      'date': 'last edit time' # optinal
    }
    """

    COLLECTION_NAME = 'Page'
    DB_NAME = 'Pageman'

    ID = '_id'
    TITLE = 'p_title'
    CONTENT = 'p_content'
    DATE = 'p_date'

    
    def __init__(self, mongodb_url=None, db_name=DB_NAME, port=None):
        self.mongodb_url = mongodb_url
        self.port = port
        self._client = None
        self.COLLECTION_NAME = COLLECTION_NAME

    def __enter__(self):
        self.connect()
        return self

    def __exit__(self):
        self.connectiont.close()

    def connect(self):
        assert self.url is not None
        self._client = pymongo.MongoClient(self.host, self.port)
        self._db = self._client[db_name]

    def getEntries(self, _from=None, _to=None):
        _skip = 0 if _from is None else _from
        _limit = 0 if _to is None else to - skip
        return self._db[self.COLLECTION_NAME].find(skip=_skip, limit=_limit).sort([(Entry.FIELD_DATE, pymongo.DESCENDING)])